### ISSUE TITLE
Roll back changes 

### ISSUE THREAD

**Issue by mts299** [SuperDARN/hdw#3]
@egthomas can you please roll back your changes of the new format. This was not agreed upon in our DAWG meeting as pyDARN needs to have time to adjust to the new format since we pull from the master of this repo everytime someone does an install.

**Comment by egthomas** [comment]
@mts299 no changes were made to the default branch (`master`).

I copied the changes from RST to a new branch called `main` which is intended to allow pydarn and other software packages to perform testing before any official roll out of the new file format.

**Comment by mts299** [comment]
Master will become main at some point as github is making the transition. Also this not what we discussed in the meeting where I asked if you could make a PR. A PR allows for awareness of the changes for those not in RST and allows for use to have discussion if anything comes up with other Software like pyDARN.  

Again please rollback the changes and make a appropriate PR such when we merge they will go to the default branch that software pulls from.
